### ISSUE TITLE
:add_on => :prepend not working

### ISSUE THREAD

**Issue by rtacconi** [stouset/twitter_bootstrap_form_for#36]
I tried this:

```
  = f.text_field :price, 'Twitter', :class => 'medium', :add_on => :prepend do
    %span.add-on @
```

but this

<span class="add-on">@</span>

it is rendered after the text_field not before, so the @ appears after the field

**Comment by stouset** [comment]
This is handled by the Bootstrap CSS styles, specifically:

``` css
.input-prepend .add-on, .input-append .add-on {
  float: left;
}
```

You can also see in my example image that it works as expected.

![](https://github.com/stouset/twitter_bootstrap_form_for/raw/master/examples/screenshot.png)
